name: Haskell Integration

on:
  push: {}

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 17 * * *"

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - latest
          - "8.10.7"
          - "8.8.4"
          - "8.6.5"
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Update Hackage snapshot
        run: cabal update

      - name: Configure library
        run: cabal configure --enable-documentation --disable-optimization

      - name: Build library
        run: cabal build

      - name: Run tests
        run: cabal test

  HLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1.2
        with:
          ghc-version: "8.10.7"

      - name: Update Hackage snapshot
        run: cabal update

      - name: Install HLint
        run: cabal install --installdir=. hlint --constraint 'hlint >= 3.3'

      - name: Run HLint
        run: ./hlint .
