name: Haskell Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  ghc-8-10-1_cabal-3-2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.1'
        cabal-version: '3.2'

    - name: Update Hackage snapshot
      run: cabal update

    - name: Build everything
      run: cabal configure --enable-documentation --disable-optimization

    - name: Build library
      run: cabal build

    - name: Run tests
      run: cabal test

  ghc-8-8-3_cabal-3-2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        cabal-version: '3.2'

    - name: Update Hackage snapshot
      run: cabal update

    - name: Build everything
      run: cabal configure --enable-documentation --disable-optimization

    - name: Build library
      run: cabal build

    - name: Run tests
      run: cabal test

  ghc-8-6-5_cabal-3-2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.2'

    - name: Update Hackage snapshot
      run: cabal update

    - name: Build everything
      run: cabal configure --enable-documentation --disable-optimization

    - name: Build library
      run: cabal build

    - name: Run tests
      run: cabal test
