name: Haskell Integration

on:
  push:
    branches:
      - master
      - feature/*

    tags:
      - "v*"

  pull_request:
    branches:
      - master

  schedule:
    - cron: "0 17 * * *"

jobs:
  BuildAndTest:
    name: Haskell Integration
    uses: vapourismo/workflows/.github/workflows/haskell-build-and-test.yaml@master
    with:
      ghc-versions: 9.2.1 9.0.2 8.10.7 8.8.4 8.6.5
      unstable-ghc-versions: latest

  HLint:
    uses: vapourismo/workflows/.github/workflows/haskell-hlint.yaml@master
    with:
      paths: lib test

  Hackage:
    name: Hackage
    needs:
      - BuildAndTest
      - HLint
    uses: vapourismo/workflows/.github/workflows/haskell-hackage-upload.yaml@master
    with:
      package-name: ${{ github.event.repository.name }}
      environment: hackage
    secrets:
      hackage-user: ${{ secrets.HACKAGE_USER }}
      hackage-password: ${{ secrets.HACKAGE_PASSWORD }}
